
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x210")
window.configure(bg = "#3D3D3D")


queue = Canvas(
    window,
    bg = "#3D3D3D",
    height = 210,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

queue.place(x = 0, y = 0)
queue.create_rectangle(
    7.0,
    7.0,
    300.0,
    71.0,
    fill="#454545",
    outline="")

queue.create_rectangle(
    7.0,
    71.0,
    300.0,
    138.0,
    fill="#4B4B4B",
    outline="")

queue.create_rectangle(
    7.0,
    138.0,
    300.0,
    202.0,
    fill="#454545",
    outline="")

queue.create_rectangle(
    300.0,
    7.0,
    593.0,
    71.0,
    fill="#4B4B4B",
    outline="")

queue.create_rectangle(
    300.0,
    71.0,
    593.0,
    138.0,
    fill="#454545",
    outline="")

queue.create_rectangle(
    300.0,
    138.0,
    593.0,
    202.0,
    fill="#4B4B4B",
    outline="")

queue.create_text(
    20.0,
    24.0,
    anchor="nw",
    text="1",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    20.0,
    89.0,
    anchor="nw",
    text="2",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    313.0,
    24.0,
    anchor="nw",
    text="4",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    313.0,
    155.0,
    anchor="nw",
    text="6",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    20.0,
    155.0,
    anchor="nw",
    text="3",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    313.0,
    90.0,
    anchor="nw",
    text="5",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 24 * -1)
)

queue.create_text(
    53.0,
    11.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    53.0,
    39.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    254.0,
    29.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    53.0,
    74.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    53.0,
    103.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    254.0,
    94.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    53.0,
    142.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    53.0,
    169.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    254.0,
    159.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    346.0,
    11.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    346.0,
    38.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    547.0,
    29.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    346.0,
    75.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    346.0,
    103.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    547.0,
    94.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    346.0,
    143.0,
    anchor="nw",
    text="Link: ",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    346.0,
    169.0,
    anchor="nw",
    text="Included text:",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    547.0,
    159.0,
    anchor="nw",
    text="0%",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 18 * -1)
)

queue.create_text(
    54.0,
    24.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    24.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    52.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    88.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    117.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    154.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    347.0,
    182.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    55.0,
    87.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    54.0,
    52.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    55.0,
    120.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    53.0,
    153.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)

queue.create_text(
    54.0,
    185.0,
    anchor="nw",
    text=".",
    fill="#A5A5A5",
    font=("ReadexPro Regular", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
